package ovs;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 File Name:	
Programmer:	Cole Becker
Date:		April 3rd 2024
Purpose:        To modify the existing car inventory program to be reused as a employee record application 
                software to keep all the employees records

 */

// Define class employees
class employees {
    String employeeID, first_name, last_name, annualSalary, start_date;

    employees (String _employeeID, String _first_name, String _last_name, String _annualSalary, String _start_date) {
        employeeID = _employeeID;
        first_name = _first_name;
        last_name = _last_name;
        annualSalary = _annualSalary;
        start_date = _start_date;
    }
}
/**
 *
 * @author User
 */
public class EmployeeRecordView extends javax.swing.JFrame {
    /** Define the ArrayList */
    ArrayList <employees> records = new ArrayList <employees>();

    /**
     * Creates new form CarExampleView
     */
    public EmployeeRecordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        List = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        employeeIn = new javax.swing.JTextField();
        firstIn = new javax.swing.JTextField();
        lastIn = new javax.swing.JTextField();
        salaryIn = new javax.swing.JTextField();
        dateIn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryOut = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Records Apllication");
        setBackground(new java.awt.Color(0, 0, 0));

        Add.setBackground(new java.awt.Color(0, 255, 51));
        Add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Remove.setBackground(new java.awt.Color(255, 0, 0));
        Remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        List.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        List.setText("List");
        List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        employeeIn.setActionCommand("yearIn");
        employeeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeInActionPerformed(evt);
            }
        });

        firstIn.setActionCommand("companyIn");

        dateIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateInActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Employee Records");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID #");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Annual Salary");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Start Date (DD/MM/YY)");

        inventoryOut.setEditable(false);
        inventoryOut.setColumns(20);
        inventoryOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inventoryOut.setRows(5);
        jScrollPane2.setViewportView(inventoryOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(firstIn)
                        .addComponent(jLabel2)
                        .addComponent(lastIn)
                        .addComponent(employeeIn)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(salaryIn)
                        .addComponent(dateIn))
                    .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(employeeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addComponent(lastIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salaryIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeInActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        employees c;
        String employeeID, first_name, last_name, annualSalary, start_date; // define variables

        // Store textbox values into the variables
        employeeID = employeeIn.getText();
        first_name = firstIn.getText();
        last_name = lastIn.getText();
        annualSalary = salaryIn.getText();
        start_date = dateIn.getText();
        
        if (employeeID.isEmpty()){ // checks to see if employeeID is empty
            JOptionPane.showMessageDialog(null, "Error, please enter valid employeeID."); // prints error if employeeID is empty
        } else {
            try {
                int employeeIDInt = Integer.parseInt(employeeID);

                c = new employees(employeeID, first_name, last_name, annualSalary, start_date); 
                records.add(c);
        
                // Clear textboxes after adding to inventory
                employeeIn.setText("");
                firstIn.setText("");
                lastIn.setText("");
                salaryIn.setText("");
                dateIn.setText(""); 
            } catch(NumberFormatException e) { // if employeeIDInt isn't a integer catch here as number format exception and show messaged dialog of error
                JOptionPane.showMessageDialog(null, "Error, please enter a valid number for ID#.");
            }
        }
    }//GEN-LAST:event_AddActionPerformed

    private void ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListActionPerformed
        String temp="";

        for (int x=0; x<=records.size()-1; x++) {
            temp = temp + records.get(x).employeeID + " "
                    + records.get(x).first_name + " "
                    + records.get(x).last_name + " "
                    + records.get(x).annualSalary + " "
                    + records.get(x).start_date + "\n"; // displays the info of the array list as strings
        }
        inventoryOut.setText(temp);
    }//GEN-LAST:event_ListActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // add a button to close the program
    }//GEN-LAST:event_ExitActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        String employeeRemove = employeeIn.getText();
        boolean found = false; // create boolean variable for finding number in list
        
        for (int x = 0; x < records.size(); x++){
            if (records.get(x).employeeID.equals(employeeRemove)){
                records.remove(x);
                JOptionPane.showMessageDialog(null, "Employee ID #" + employeeIn.getText() + " was succesfully removed."); // shows popup of correct employee id that was removed
                found = true; // if the employee id # is found

                // Clear textboxes after removing to applicants
                employeeIn.setText("");
                firstIn.setText("");
                lastIn.setText("");
                salaryIn.setText("");
                dateIn.setText("");
                break;
            }
        }
        if (!found){ // if the id is not found
            JOptionPane.showMessageDialog(null, "Error, employee ID #" + employeeIn.getText() + " was not found in records."); // show message dialog saying error
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void dateInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRecordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Exit;
    private javax.swing.JButton List;
    private javax.swing.JButton Remove;
    private javax.swing.JTextField dateIn;
    private javax.swing.JTextField employeeIn;
    private javax.swing.JTextField firstIn;
    private javax.swing.JTextArea inventoryOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastIn;
    private javax.swing.JTextField salaryIn;
    // End of variables declaration//GEN-END:variables
}
