/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jSleep;

/**
 *
 * @author rando
 */
public class JavaSleepTimer extends javax.swing.JFrame {

    /**
     * Creates new form JavaSleepTimer
     */
    public JavaSleepTimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        txtInputBirthdate = new javax.swing.JLabel();
        txtInputCurrentDay = new javax.swing.JLabel();
        txtBirthDMY = new javax.swing.JLabel();
        txtTodayDMY = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtTotalDays = new javax.swing.JTextField();
        txtTotalHoursSleep = new javax.swing.JTextField();
        InputBirthD = new javax.swing.JTextField();
        InputBirthM = new javax.swing.JTextField();
        InputBirthY = new javax.swing.JTextField();
        InputTodayD = new javax.swing.JTextField();
        InputTodayM = new javax.swing.JTextField();
        InputTodayY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SleepTimer");

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(102, 0, 0));
        title.setText("Sleep Calculator");

        txtInputBirthdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtInputBirthdate.setForeground(new java.awt.Color(0, 0, 0));
        txtInputBirthdate.setText("Enter your birthdate");

        txtInputCurrentDay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtInputCurrentDay.setForeground(new java.awt.Color(0, 0, 0));
        txtInputCurrentDay.setText("Enter todays date");

        txtBirthDMY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtBirthDMY.setForeground(new java.awt.Color(0, 0, 0));
        txtBirthDMY.setText("  D        M         Y");

        txtTodayDMY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTodayDMY.setForeground(new java.awt.Color(0, 0, 0));
        txtTodayDMY.setText("  D        M         Y");

        btnTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTotal.setText("Calculate");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtTotalDays.setEditable(false);
        txtTotalDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDaysActionPerformed(evt);
            }
        });

        txtTotalHoursSleep.setEditable(false);
        txtTotalHoursSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHoursSleepActionPerformed(evt);
            }
        });

        InputBirthD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InputBirthD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputBirthDActionPerformed(evt);
            }
        });

        InputBirthM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        InputBirthY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        InputTodayD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        InputTodayM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        InputTodayY.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalDays, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHoursSleep, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInputBirthdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(txtInputCurrentDay)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InputBirthD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputBirthM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputBirthY, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputTodayD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputTodayM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(InputTodayY, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBirthDMY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTodayDMY)
                        .addGap(84, 84, 84))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputBirthdate)
                    .addComponent(txtInputCurrentDay))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputBirthD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputBirthM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputBirthY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTodayD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTodayM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTodayY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirthDMY)
                    .addComponent(txtTodayDMY))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHoursSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalHoursSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHoursSleepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHoursSleepActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // Close the program when button pressed
    }//GEN-LAST:event_btnExitActionPerformed

    private void InputBirthDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputBirthDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputBirthDActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int DiffD, DiffM, DiffY, TotalAliveDays; // Variables
        DiffD = Integer.parseInt(InputTodayD.getText()) - Integer.parseInt(InputBirthD.getText()); // Calculates difference of days
        DiffM = Integer.parseInt(InputTodayM.getText()) - Integer.parseInt(InputBirthM.getText()); // Calculates difference of months
        DiffY = Integer.parseInt(InputTodayY.getText()) - Integer.parseInt(InputBirthY.getText()); // Calculates difference of years
        TotalAliveDays = (DiffD + (DiffM * 30) + (DiffY * 365)); // Total number of days alive
        
        int TotalHoursSlept;
        TotalHoursSlept = TotalAliveDays * 8; // Calculates total hours slept assuming 8 hours sleep
        
        txtTotalDays.setText("You have been alive for " + TotalAliveDays + " days!"); // Displays total alive days in bottom right box
        txtTotalHoursSleep.setText("You have slept for " + TotalHoursSlept + " hours!"); // Displays total hours slept in bottom right box
    }//GEN-LAST:event_btnTotalActionPerformed

    private void txtTotalDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaSleepTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaSleepTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaSleepTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaSleepTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaSleepTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputBirthD;
    private javax.swing.JTextField InputBirthM;
    private javax.swing.JTextField InputBirthY;
    private javax.swing.JTextField InputTodayD;
    private javax.swing.JTextField InputTodayM;
    private javax.swing.JTextField InputTodayY;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txtBirthDMY;
    private javax.swing.JLabel txtInputBirthdate;
    private javax.swing.JLabel txtInputCurrentDay;
    private javax.swing.JLabel txtTodayDMY;
    private javax.swing.JTextField txtTotalDays;
    private javax.swing.JTextField txtTotalHoursSleep;
    // End of variables declaration//GEN-END:variables
}
